/*****************************************************************************************************
 * SVL - Simple Visual Library
 *----------------------------------------------------------------------------------------------------
 * Author : Sergey Kharchenko (xksv@mail.ru)
 * Version: 1.0
 * Status : alpha
 * Tested : Microsoft Visual C++ 2010, GCC MinGW 4.5.2
 *----------------------------------------------------------------------------------------------------
 * License: http://www.boost.org/LICENSE_1_0.txt
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, 
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *****************************************************************************************************/

#ifndef SVL_GUI_HPP
#define SVL_GUI_HPP

#include <svl/base/environment.hpp>
#include <svl/base/exceptions.hpp>
#include <svl/base/graphics.hpp>
#include <svl/base/timer.hpp>
#include <svl/base/form.hpp>
#include <svl/base/dialogs.hpp>
#include <svl/base/widget.hpp>
#include <svl/base/user_widget.hpp>
#include <svl/widgets/group_box.hpp>
#include <svl/widgets/button.hpp>
#include <svl/widgets/line_edit.hpp>
#include <svl/widgets/radio_button.hpp>
#include <svl/widgets/panel.hpp>
#include <svl/widgets/label.hpp>
#include <svl/widgets/check_box.hpp>
#include <svl/widgets/progress_bar.hpp>
#include <svl/widgets/combo_box.hpp>
#include <svl/widgets/combo_edit.hpp>
#include <svl/widgets/push_button.hpp>
#include <svl/widgets/list_box.hpp>

#endif // SVL_GUI_HPP
