/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef camera2_CONSTANTS_H
#define camera2_CONSTANTS_H

#include "camera2_types.h"

namespace rubetek { namespace tag { namespace camera2 {

class camera2Constants {
 public:
  camera2Constants();

};

extern const camera2Constants g_camera2_constants;

}}} // namespace

#endif
