/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef device_CONSTANTS_H
#define device_CONSTANTS_H

#include "device_types.h"

namespace rubetek { namespace proto { namespace imc {

class deviceConstants {
 public:
  deviceConstants();

};

extern const deviceConstants g_device_constants;

}}} // namespace

#endif
