/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef functional_CONSTANTS_H
#define functional_CONSTANTS_H

#include "functional_types.h"

namespace rubetek { namespace tag { namespace functional {

class functionalConstants {
 public:
  functionalConstants();

};

extern const functionalConstants g_functional_constants;

}}} // namespace

#endif
