/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef home_builder_CONSTANTS_H
#define home_builder_CONSTANTS_H

#include "home_builder_types.h"

namespace rubetek { namespace tag { namespace homebuilder {

class home_builderConstants {
 public:
  home_builderConstants();

};

extern const home_builderConstants g_home_builder_constants;

}}} // namespace

#endif
