/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef homekit_bridge_CONSTANTS_H
#define homekit_bridge_CONSTANTS_H

#include "homekit_bridge_types.h"

namespace rubetek { namespace tag { namespace homekit_bridge {

class homekit_bridgeConstants {
 public:
  homekit_bridgeConstants();

};

extern const homekit_bridgeConstants g_homekit_bridge_constants;

}}} // namespace

#endif
