/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef imc_CONSTANTS_H
#define imc_CONSTANTS_H

#include "imc_types.h"

namespace rubetek { namespace proto { namespace imc {

class imcConstants {
 public:
  imcConstants();

};

extern const imcConstants g_imc_constants;

}}} // namespace

#endif
