/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef notification_CONSTANTS_H
#define notification_CONSTANTS_H

#include "notification_types.h"

namespace rubetek { namespace tag { namespace notification {

class notificationConstants {
 public:
  notificationConstants();

};

extern const notificationConstants g_notification_constants;

}}} // namespace

#endif
