/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef o7_CONSTANTS_H
#define o7_CONSTANTS_H

#include "o7_types.h"

namespace rubetek { namespace tag { namespace o7 {

class o7Constants {
 public:
  o7Constants();

};

extern const o7Constants g_o7_constants;

}}} // namespace

#endif
