/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef property_CONSTANTS_H
#define property_CONSTANTS_H

#include "property_types.h"

namespace rubetek { namespace proto { namespace imc {

class propertyConstants {
 public:
  propertyConstants();

};

extern const propertyConstants g_property_constants;

}}} // namespace

#endif
