/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rf_CONSTANTS_H
#define rf_CONSTANTS_H

#include "rf_types.h"

namespace rubetek { namespace tag { namespace rf {

class rfConstants {
 public:
  rfConstants();

};

extern const rfConstants g_rf_constants;

}}} // namespace

#endif
