/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rtsp_server_relay_CONSTANTS_H
#define rtsp_server_relay_CONSTANTS_H

#include "rtsp_server_relay_types.h"

namespace rubetek { namespace tag { namespace rtsp_server_relay {

class rtsp_server_relayConstants {
 public:
  rtsp_server_relayConstants();

};

extern const rtsp_server_relayConstants g_rtsp_server_relay_constants;

}}} // namespace

#endif
