/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef rtsp_relay_CONSTANTS_H
#define rtsp_relay_CONSTANTS_H

#include "rtsp_relay_types.h"

namespace rubetek { namespace tag { namespace rtsp_relay {

class rtsp_relayConstants {
 public:
  rtsp_relayConstants();

};

extern const rtsp_relayConstants g_rtsp_relay_constants;

}}} // namespace

#endif
