/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef script_CONSTANTS_H
#define script_CONSTANTS_H

#include "script_types.h"

namespace rubetek { namespace tag { namespace script {

class scriptConstants {
 public:
  scriptConstants();

};

extern const scriptConstants g_script_constants;

}}} // namespace

#endif
