/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef server_auxiliary_CONSTANTS_H
#define server_auxiliary_CONSTANTS_H

#include "server_auxiliary_types.h"

namespace rubetek { namespace proto {

class server_auxiliaryConstants {
 public:
  server_auxiliaryConstants();

};

extern const server_auxiliaryConstants g_server_auxiliary_constants;

}} // namespace

#endif
