/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef statistics_CONSTANTS_H
#define statistics_CONSTANTS_H

#include "statistics_types.h"

namespace rubetek { namespace tag { namespace statistics {

class statisticsConstants {
 public:
  statisticsConstants();

};

extern const statisticsConstants g_statistics_constants;

}}} // namespace

#endif
