/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef upnp_CONSTANTS_H
#define upnp_CONSTANTS_H

#include "upnp_types.h"

namespace rubetek { namespace tag { namespace upnp {

class upnpConstants {
 public:
  upnpConstants();

};

extern const upnpConstants g_upnp_constants;

}}} // namespace

#endif
