/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef video_recorder_CONSTANTS_H
#define video_recorder_CONSTANTS_H

#include "video_recorder_types.h"

namespace rubetek { namespace tag { namespace videorecorder {

class video_recorderConstants {
 public:
  video_recorderConstants();

};

extern const video_recorderConstants g_video_recorder_constants;

}}} // namespace

#endif
