/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef video_uploader_CONSTANTS_H
#define video_uploader_CONSTANTS_H

#include "video_uploader_types.h"

namespace rubetek { namespace tag { namespace video_uploader {

class video_uploaderConstants {
 public:
  video_uploaderConstants();

};

extern const video_uploaderConstants g_video_uploader_constants;

}}} // namespace

#endif
