/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef wifi_device_CONSTANTS_H
#define wifi_device_CONSTANTS_H

#include "wifi_device_types.h"

namespace rubetek { namespace tag { namespace wifidevice {

class wifi_deviceConstants {
 public:
  wifi_deviceConstants();

};

extern const wifi_deviceConstants g_wifi_device_constants;

}}} // namespace

#endif
