/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef zwave_CONSTANTS_H
#define zwave_CONSTANTS_H

#include "zwave_types.h"

namespace rubetek { namespace tag { namespace zwave {

class zwaveConstants {
 public:
  zwaveConstants();

};

extern const zwaveConstants g_zwave_constants;

}}} // namespace

#endif
