/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cl_CONSTANTS_H
#define cl_CONSTANTS_H

#include "cl_types.h"

namespace rubetek { namespace proto {

class clConstants {
 public:
  clConstants();

};

extern const clConstants g_cl_constants;

}} // namespace

#endif
