/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cl_protocol_CONSTANTS_H
#define cl_protocol_CONSTANTS_H

#include "cl_protocol_types.h"

namespace rubetek { namespace proto {

class cl_protocolConstants {
 public:
  cl_protocolConstants();

};

extern const cl_protocolConstants g_cl_protocol_constants;

}} // namespace

#endif
