/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cl_TYPES_H
#define cl_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include "general_types.h"
#include "cl_protocol_types.h"
#include "ihap_types.h"
#include "cl_version_types.h"
#include "ihap_version_types.h"


namespace rubetek { namespace proto {

}} // namespace

#endif
