/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cl_version_CONSTANTS_H
#define cl_version_CONSTANTS_H

#include "cl_version_types.h"

namespace rubetek { namespace proto {

class cl_versionConstants {
 public:
  cl_versionConstants();

  int32_t cl_version;
};

extern const cl_versionConstants g_cl_version_constants;

}} // namespace

#endif
