/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ihap_version_CONSTANTS_H
#define ihap_version_CONSTANTS_H

#include "ihap_version_types.h"

namespace rubetek { namespace proto {

class ihap_versionConstants {
 public:
  ihap_versionConstants();

  int32_t ihap_version;
};

extern const ihap_versionConstants g_ihap_version_constants;

}} // namespace

#endif
