/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ihap_CONSTANTS_H
#define ihap_CONSTANTS_H

#include "ihap_types.h"

namespace rubetek { namespace proto { namespace ihap {

class ihapConstants {
 public:
  ihapConstants();

};

extern const ihapConstants g_ihap_constants;

}}} // namespace

#endif
