/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef version_CONSTANTS_H
#define version_CONSTANTS_H

#include "version_types.h"

namespace rubetek { namespace proto {

class versionConstants {
 public:
  versionConstants();

};

extern const versionConstants g_version_constants;

}} // namespace

#endif
