#pragma once

#define MSW_NO_THRIFT_VERSION_HPP

#include <msw/config.hpp>

#define MSW_DISABLE_LARGE_FILE

#include <msw/file/file.hpp>

#define MSW_NO_MOVE_STD_FUNCTION // for ios
#ifndef MSW_NO_TO_STRING
#   define MSW_NO_TO_STRING      // for ios
#endif

#ifdef MSW_LINUX
#   define SMART_HOUSE_EXPLICIT_DEFINE_CONFIG_FILE
#   define SMART_HOUSE_HARD_CONTENTS_CONFIG_FILE
#endif

#define RUBETEK_HEADER_ONLY
#ifdef RUBETEK_CONTROLLER_LINK_LIBRARY
#   define RUBETEK_INLINE_OF_IMPL
#else
#   define RUBETEK_INLINE_OF_IMPL inline
#endif

//#define RUBETEK_THRIFT_GENERAL_LOG
//#define RUBETEK_THRIFT_TRANSCEIVER_LOG
//#define RUBETEK_IHLP_TRANSCEIVER_BASE_LOG
//#define RUBETEK_CLIENT_IHAP_LOG
//#define RUBETEK_CLIENT_CONTROLLER_LINK_LOG
//#define RUBETEK_CLIENT_CONTROLLERS_UNIT_LOG
//#define RUBETEK_CLIENT_CALLBACK_SERVICE_LOG
//#define RUBETEK_CLIENT_SERVER_TRANSCEIVER_LOG

//#define RUBETEK_CLIENT_CONTROLLER_LINK_TICKS
